// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJFts6YinA_g2eNRKawWpSHBuvfc0OR-o',
    appId: '1:1085897852691:web:547a40f25e97774b563ce6',
    messagingSenderId: '1085897852691',
    projectId: 'saferoute-3fd1a',
    authDomain: 'saferoute-3fd1a.firebaseapp.com',
    storageBucket: 'saferoute-3fd1a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqRvprx0YU_u6cWluAXWQgAofd3Bklby4',
    appId: '1:1085897852691:android:4d008a493cc56fed563ce6',
    messagingSenderId: '1085897852691',
    projectId: 'saferoute-3fd1a',
    storageBucket: 'saferoute-3fd1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoMzLxekacfDBH9DdN5tj1v6rCfr4yX6M',
    appId: '1:1085897852691:ios:80e61fa46d1b2c14563ce6',
    messagingSenderId: '1085897852691',
    projectId: 'saferoute-3fd1a',
    storageBucket: 'saferoute-3fd1a.firebasestorage.app',
    iosBundleId: 'com.example.saferoute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoMzLxekacfDBH9DdN5tj1v6rCfr4yX6M',
    appId: '1:1085897852691:ios:80e61fa46d1b2c14563ce6',
    messagingSenderId: '1085897852691',
    projectId: 'saferoute-3fd1a',
    storageBucket: 'saferoute-3fd1a.firebasestorage.app',
    iosBundleId: 'com.example.saferoute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJFts6YinA_g2eNRKawWpSHBuvfc0OR-o',
    appId: '1:1085897852691:web:c508328051e02a6d563ce6',
    messagingSenderId: '1085897852691',
    projectId: 'saferoute-3fd1a',
    authDomain: 'saferoute-3fd1a.firebaseapp.com',
    storageBucket: 'saferoute-3fd1a.firebasestorage.app',
  );
}
